created documentation files for best practices
fastn-stack/fastn.io pull request #127
Opened 2023-04-04 14:44 UTC by gargajit

Created this PR to document the Code best practices.

2023-04-04 15:02 UTC, amitu requested changes

2023-04-05 09:04 UTC, Arpita-Jaiswal requested changes

2023-04-05 09:26 UTC, amitu commented
@gargajit comment when all the requested changes are done.

2023-04-05 11:51 UTC, gargajit commented on FASTN.ftd
> +-- fastn.auto-import: fastn.io/utils as utils
At this point, yes, it was used only in one or two files, but in future, as the documentation of best-practices grows, I will keep on using the components inside this utils file.
I have already used it in 5 files in the latest commit.

2023-04-05 11:53 UTC, gargajit commented on FASTN.ftd
> +  -
this is outdated as I have fixed it in the latest commit.

2023-04-06 04:49 UTC, amitu commented on FASTN.ftd
> +-- fastn.auto-import: fastn.io/utils as utils
It is still not going to be almost all files. Right now there are 162 files in fastn.io. Almost all means what 90%? 3% can't be "almost all" right?

And whenever it start being used in more files add it to auto import. Do not violate the guidelines. Or update the guideline for whatever exception you think you are invoking.

2023-04-06 08:18 UTC, Arpita-Jaiswal requested changes

2023-04-06 08:18 UTC, Arpita-Jaiswal commented on best-practices/use-conditions.ftd
> +element and then include any necessary child within that element.
```suggestion
Instead, it is recommended to apply conditions only to the element
itself, and omit applying conditions to its children.
```

2023-04-06 08:18 UTC, Arpita-Jaiswal commented on utils.ftd
> +;; border-top-right-radius.px: 4
```suggestion
```

2023-04-06 08:18 UTC, Arpita-Jaiswal commented on utils.ftd
> +;; border-radius.px: 12
```suggestion
```

Remove comments

2023-04-06 09:10 UTC, merged